version: "3.8"

services:
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"   # Public entrypoint for APIs
      - "8001:8001"   # Kong Admin API
      - "8443:8443"   # HTTPS
      - "8444:8444"   # Kong Admin API HTTPS
    volumes:
      - ./kong.yml:/kong/kong.yml

  scanner1:
    build: ./scanner1
    ports:
      - "5001:5001"

  scanner2:
    build: ./scanner2
    ports:
      - "5002:5002"
