

version: '3.8'

services:
  
  kong:
    image: kong:latest               
    container_name: kong-gateway
    environment:
      
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      # Standard logging settings.
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      
      - ./kong/kong.yml:/etc/kong/kong.yml
    ports:
      
      - "8000:8000"   
      - "8443:8443"   
      - "8001:8001"   
    networks:
      - default
    restart: always

  master:
    build: ./master
   
    depends_on:
      - scanner1
      - scanner2
      - db
    environment:
      FLASK_DEBUG: 0
    networks:
      - default
    restart: always

  
  scanner1:
    build: ./scanner1
    ports:
      - "5001"
    environment:
      FLASK_DEBUG: 0
    networks:
      - default

  scanner2:
    build: ./scanner2
    ports:
      - "5002"
    environment:
      FLASK_DEBUG: 0
    networks:
      - default

  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scandb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

volumes:
  dbdata:

networks:
  default:
    driver: bridge