apiVersion: v1
kind: Service
metadata:
  name: scanner3-service
spec:
  selector:
    app: scanner3
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer
