apiVersion: v1
kind: Service
metadata:
  name: scanner1-service
spec:
  selector:
    app: scanner1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
