apiVersion: v1
kind: Service
metadata:
  name: scanner2-service
spec:
  selector:
    app: scanner2
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
